services:
  teable:
    image: ghcr.io/teableio/teable:latest
    deploy:
      replicas: 2
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.teable.loadbalancer.server.port=3000'
      - 'traefik.http.routers.teable.rule=Host(`example.netvpc.com`)'
      - 'traefik.http.routers.teable.service=teable'
      - 'traefik.http.routers.teable.entrypoints=websecure'
      - 'traefik.http.routers.teable.tls=true'
      - 'traefik.http.routers.teable.tls.certresolver=letsencrypt'
    volumes:
      - ./teable-data:/app/.assets:rw
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE}
      - NEXT_ENV_IMAGES_ALL_REMOTE=true
    networks:
      - traefik-network
      - teable-network
    depends_on:
      teable-db-migrate:
        condition: service_completed_successfully
      teable-cache:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 3

  teable-db-migrate:
    image: ghcr.io/teableio/teable-db-migrate:latest
    environment:
      - TZ=${TIMEZONE}
      - PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    networks:
      - teable-network

  teable-cache:
    image: redis:7-bookworm
    container_name: teable-cache
    restart: always
    volumes:
      - teable-cache:/data:rw
      # you may use a bind-mounted host directory instead,
      # so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/cache/data:/data:rw
    networks:
      - teable-network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  teable-network:
    external: true
  traefik-network:
    external: true

volumes:
  teable-db: {}
  teable-cache: {}
  teable-storage: {}
  teable-data: {}
